// TXT 打卡点数据。字段见模板说明。出处缩写:
// 具体出处(博主)见 来源明细_内部.json,不上线
window.MAP_SPOTS = [
 {id:1, city:"首尔", zh:"大黑旧址", kr:"빅히트 구사옥", cat:"地标", area:"江南·论岘", members:["全员"], addr:"서울 강남구 도산대로16길 13-20", sub:"旁边有一家CU,一个大坡上去就是;地铁公交都能到", src:"粉丝实测攻略", conf:"中", mapq:"도산대로16길 13-20"},
 {id:2, city:"首尔", zh:"Amy's coffee", kr:"에이미스커피", cat:"咖啡·点心", area:"江南·论岘", members:["全员"], addr:"서울 강남구 도산대로26길 11 신천빌딩 1층", sub:"店里有一整面TXT周边海报墙;一进门就是同款座位;然竣同款香蕉奶昔", src:"粉丝实测攻略", conf:"中", mapq:"도산대로26길 11"},
 {id:3, city:"首尔", zh:"姜太显初中", kr:"", cat:"地标", area:"江南·论岘", members:["姜太显"], addr:"서울 강남구 도산대로38길 27", sub:"大黑旧址附近,可一起打卡;学校请在外面拍照", src:"粉丝实测攻略", conf:"中", mapq:"도산대로38길 27"},
 {id:4, city:"首尔", zh:"BetterDay 黑芝麻咖啡", kr:"베러데이", cat:"咖啡·点心", area:"弘大", members:["崔然竣"], addr:"서울특별시 마포구 어울마당로 147", sub:"然竣点的黑芝麻拿铁;不能用微信支付", src:"多篇粉丝实测攻略互相印证", conf:"高", mapq:"어울마당로 147"},
 {id:5, city:"首尔", zh:"WORKSOUT 弘大RISE店", kr:"웍스아웃 홍대 라이즈", cat:"购物", area:"弘大", members:["崔然竣"], addr:"서울 마포구 양화로 130", sub:"导航只到RISE门口:进一楼(自习室样)→电梯上3楼→潮牌店往里的巷子拐过去就是同款镜子", src:"多篇粉丝实测攻略互相印证", conf:"高", mapq:"양화로 130 웍스아웃"},
 {id:6, city:"首尔", zh:"彼得潘唱片店", kr:"", cat:"购物", area:"弘大", members:["崔然竣"], addr:"서울 마포구 양화로18안길 28 지하", sub:"在地下一层;营业时间不固定,去前查Naver", src:"多篇粉丝实测攻略互相印证", conf:"高", mapq:"양화로18안길 28"},
 {id:7, city:"首尔", zh:"HYBE大楼", kr:"하이브", cat:"地标", area:"龙山", members:["全员"], addr:"서울특별시 용산구 한강대로 42", sub:"后门常有粉丝应援、地铁站大屏/站牌应援", src:"多篇粉丝实测攻略互相印证", conf:"高", mapq:"하이브 용산"},
 {id:8, city:"首尔", zh:"汝矣岛汉江公园", kr:"여의도 한강공원", cat:"地标", area:"汝矣岛", members:["崔然竣"], addr:"汝矣渡口站(여의나루역)3号口出来往汉江方向", sub:"汉江然竣同款;具体同款位置未标", src:"多篇粉丝实测攻略互相印证", conf:"高", mapq:"여의도 한강공원"},
 {id:9, city:"首尔", zh:"岛山公园", kr:"도산공원", cat:"地标", area:"狎鸥亭", members:["崔然竣"], addr:"서울 강남구 도산대로45길 20", sub:"狎鸥亭罗德奥站5号口约715m", src:"粉丝实测攻略", conf:"中", mapq:"도산공원"},
 {id:10, city:"首尔", zh:"Camel咖啡", kr:"카멜커피", cat:"咖啡·点心", area:"狎鸥亭", members:["崔然竣","休宁凯"], addr:"서울 강남구 도산대로45길 16-8", sub:"离岛山公园很近", src:"粉丝实测攻略", conf:"中", mapq:"도산대로45길 16-8"},
 {id:11, city:"首尔", zh:"Kuhichi 龙山", kr:"쿠히치 용산", cat:"美食", area:"龙山", members:["崔秀彬","崔然竣"], addr:"待核", sub:"同款:海鲜火锅、五花肉荞麦面", src:"粉丝实测攻略", conf:"中", mapq:"쿠히치 용산"},
 {id:12, city:"首尔", zh:"人生四格 龙山店", kr:"인생네컷", cat:"地标", area:"龙山", members:["崔秀彬","崔然竣"], addr:"待核(B写한강대로62길 37 1층;C写汉江路一街214)", sub:"有好几家分店,🦊🐰拍的是龙山这家;斜对面就是他们吃饭的饭店(C);靠近三角地站", src:"多篇粉丝实测攻略互相印证", conf:"中", mapq:"인생네컷 용산"},
 {id:13, city:"首尔", zh:"奖忠坛公园", kr:"장충단공원", cat:"地标", area:"中区·东国大", members:["崔然竣"], addr:"서울 중구 동호로 257-10", sub:"3号线东国大学站", src:"粉丝实测攻略", conf:"中", mapq:"장충단공원"},
 {id:14, city:"首尔", zh:"haus coffee&dessert", kr:"하우스 커피앤디저트", cat:"咖啡·点心", area:"中区·东国大", members:["崔然竣"], addr:"서울특별시 중구 동호로 257-8", sub:"在奖忠坛公园里;同款:牛角包/油茶面/艾草年糕冰淇淋/巧克力拿铁(热)/希腊红柿酸奶碗", src:"粉丝实测攻略", conf:"中", mapq:"동호로 257-8"},
 {id:15, city:"首尔", zh:"Covernat 圣水店", kr:"커버낫 성수", cat:"购物", area:"圣水", members:["崔秀彬"], addr:"성수동2가 316-44", sub:"可上二楼,镜子上有秀彬签名", src:"粉丝实测攻略", conf:"中", mapq:"커버낫 성수"},
 {id:16, city:"首尔", zh:"not to do 咖啡厅", kr:"", cat:"咖啡·点心", area:"龙山", members:["崔秀彬","崔杋圭"], addr:"서울특별시 용산구 한강대로 56-1 2층", sub:"HYBE附近,新龙山站走约6分钟;门口贴了节目照片", src:"粉丝实测攻略", conf:"中", mapq:"한강대로 56-1"},
 {id:17, city:"首尔", zh:"秀彬狎鸥亭同款机位", kr:"", cat:"地标", area:"狎鸥亭", members:["崔秀彬"], addr:"서울특별시 신사동 663-3번지 401호", sub:"狎鸥亭罗德奥站出来走一段;路上车多,拍完快离开", src:"粉丝实测攻略", conf:"中", mapq:"신사동 663-3"},
 {id:18, city:"首尔", zh:"秀彬同款手链店", kr:"", cat:"购物", area:"狎鸥亭", members:["崔秀彬"], addr:"서울특별시 강남구 도산대로51길 42", sub:"去前在Naver查营业时间;店里有爱豆同款手链册子,可拿照片让店员找", src:"粉丝实测攻略", conf:"中", mapq:"도산대로51길 42"},
 {id:19, city:"首尔", zh:"宇破z黑胶唱片店", kr:"", cat:"购物", area:"钟路", members:["崔杋圭","姜太显"], addr:"서울특별시 종로구 종로 154", sub:"签名在电话亭下方", src:"粉丝实测攻略", conf:"中", mapq:"종로 154"},
 {id:20, city:"首尔", zh:"南山塔", kr:"N서울타워", cat:"地标", area:"龙山·南山", members:["全员"], addr:"서울 용산구 남산공원길 105", sub:"坐公交上去后还要爬一段很陡的坡", src:"多篇粉丝实测攻略互相印证", conf:"高", mapq:"N서울타워"},
 {id:21, city:"京畿道", zh:"佛谷高中", kr:"불곡고등학교", cat:"地标", area:"城南·盆唐", members:["崔然竣"], addr:"待核(불곡고등학교)", sub:"公交下车后直接往右走!左边的佛谷中学容易搞混;学校请在外面拍照", src:"多篇粉丝实测攻略互相印证", conf:"高", mapq:"불곡고등학교"},
 {id:22, city:"京畿道", zh:"九美中学", kr:"구미중학교", cat:"地标", area:"城南·盆唐", members:["崔然竣"], addr:"京畿道 城南市 盆唐区 九美洞 299-1", sub:"攻略里写作'龟尾/鱼尾中学';从佛谷高中可走过去(上坡多);附近可去梧里站坐地铁", src:"多篇粉丝实测攻略互相印证", conf:"高", mapq:"구미중학교 성남"},
 {id:23, city:"京畿道", zh:"然竣路演广场(AK广场 盆唐)", kr:"AK플라자 분당", cat:"地标", area:"城南·盆唐", members:["崔然竣"], addr:"京畿道 城南市 盆唐区 书岘洞 263", sub:"地铁到书岘站1号口", src:"粉丝实测攻略", conf:"中", mapq:"AK플라자 분당"},
 {id:24, city:"首尔", zh:"鹤洞公园", kr:"학동공원", cat:"地标", area:"江南·论岘", members:["崔秀彬","崔杋圭"], addr:"강남구 강남대로140길 47", sub:"物料里说是两人练习生时期会去玩的地方;有两个秋千,就在大黑旧址后面一点", src:"粉丝实测攻略", conf:"中", mapq:"학동공원"},
 {id:25, city:"首尔", zh:"ALAND", kr:"에이랜드", cat:"购物", area:"待核", members:["崔然竣"], addr:"待核(原帖:直接Naver搜ALAND,未写哪家分店)", sub:"同款在店外面不在店里;楼上是然竣给成员们买衣服的地方", src:"粉丝实测攻略", conf:"低", mapq:"에이랜드"},
 {id:26, city:"首尔", zh:"南山山菜家 猪排", kr:"남산산채집", cat:"美食", area:"中区·南山", members:["崔然竣","崔杋圭"], addr:"서울 중구 소파로 95 1층", sub:"🦊🐻同款猪排", src:"粉丝实测攻略", conf:"中", mapq:"소파로 95"},
 {id:27, city:"仁川", zh:"TO DO 狗狗咖啡(Dog Camp 机场店)", kr:"도그캠프 공항점", cat:"咖啡·点心", area:"仁川机场", members:["全员"], addr:"待核", sub:"TO DO综艺同款;然竣抱的小狗叫moongchi", src:"粉丝实测攻略", conf:"中", mapq:"도그캠프 공항점"},
 {id:28, city:"京畿道", zh:"TO DO 汗蒸房(Seupadium24)", kr:"스파디움24", cat:"地标", area:"南杨州·茶山", members:["全员"], addr:"京畿道 南杨州市 茶山洞 6143", sub:"TO DO综艺同款;坐地铁到九里站再打车", src:"粉丝实测攻略", conf:"中", mapq:"스파디움24"},
 {id:29, city:"仁川", zh:"乙旺里海水浴场", kr:"을왕리해수욕장", cat:"地标", area:"永宗岛", members:["全员"], addr:"인천 중구 용유서로302번길 16-15", sub:"离仁川机场近,中午航班可先寄存行李坐公交来;附近盐面包很香", src:"粉丝实测攻略", conf:"中", mapq:"을왕리해수욕장"},
 {id:30, city:"首尔", zh:"姨母家餐厅", kr:"", cat:"美食", area:"江南·论岘", members:["全员"], addr:"서울 강남구 도산대로28길 14", sub:"练习生时期常吃的店;和大黑旧址在同一片区域", src:"粉丝实测攻略", conf:"中", mapq:"도산대로28길 14"},
 {id:31, city:"首尔", zh:"TO DO 咖啡店(Cafe 빈틈 M)", kr:"까페 빈틈 M", cat:"咖啡·点心", area:"麻浦·望远", members:["崔然竣"], addr:"서울 마포구 망원동 423-18", sub:"To Do 157期(25.06.02)去的咖啡店;🦊pick:哈密瓜苏打(메론소다)7000₩", src:"官方综艺+粉丝整理", conf:"高", mapq:"까페 빈틈 M 망원동"},
 {id:32, city:"日本·福冈", zh:"Komeda珈琲 福冈百道店", kr:"コメダ珈琲店 福岡ももち店", cat:"咖啡·点心", area:"早良区·百道", members:["崔然竣"], addr:"福岡県福岡市早良区百道浜2丁目1-22", sub:"TXT-LOG(25.06.28)去的咖啡店;🦊pick:冰淇淋蜜瓜苏打660日元(手上是外带杯,店内是小靴子杯);上海也有多家分店可打卡同款", src:"官方vlog+粉丝整理", conf:"高", mapq:"コメダ珈琲店 福岡ももち店"},
 {id:33, city:"首尔", zh:"TO DO 咖啡店(Pirultz Coffee House)", kr:"Pirultz Coffee House", cat:"咖啡·点心", area:"龙山", members:["崔秀彬","崔杋圭"], addr:"서울 용산구 한강대로 56-1 2층", sub:"To Do拍摄过的咖啡店,在二楼;离HYBE很近,打卡完可以顺路来", src:"粉丝实测攻略", conf:"中", mapq:"한강대로 56-1"},
 {id:34, city:"首尔", zh:"Bâton meal cafe", kr:"Bâton meal cafe", cat:"咖啡·点心", area:"龙山", members:["全员"], addr:"待核(龙山区,HYBE附近)", sub:"《TOMORROW》概念预告拍摄地;早午餐店;周末不接受预约", src:"粉丝实测攻略", conf:"高", mapq:"Bâton meal cafe"},
 {id:35, city:"首尔", zh:"적토발효구이 용산점", kr:"", cat:"美食", area:"龙山", members:["全员"], addr:"待核(HYBE附近)", sub:"店里有TXT全员签名;成员来这里吃过饭(有视频截图)", src:"粉丝实测攻略", conf:"高", mapq:"적토발효구이 용산점"},
 {id:36, city:"首尔", zh:"열정도고깃집", kr:"", cat:"美食", area:"龙山", members:["崔秀彬","休宁凯"], addr:"待核(龙山区)", sub:"店里有🐰🐧签名", src:"粉丝实测攻略", conf:"中", mapq:"열정도고깃집"},
 {id:37, city:"首尔", zh:"Downtowner 汉堡", kr:"다운타우너", cat:"美食", area:"待核", members:["全员"], addr:"待核(原帖未写哪家分店)", sub:"TXT同款汉堡店;首尔有多家分店", src:"粉丝实测攻略", conf:"中", mapq:"다운타우너"},
 {id:38, city:"日本·东京", zh:"Doshieobu 韩国料理", kr:"トシオブ韓国料理屋(도시어부)", cat:"美食", area:"新大久保", members:["全员"], addr:"東京都新宿区大久保2-26-1 B1", sub:"店里墙上有TXT签名;新大久保站步行约6分钟;韩式海鲜/酱蟹店", src:"粉丝实测攻略", conf:"中", mapq:"トシオブ 新宿区大久保2-26-1"},
 {id:39, city:"首尔", zh:"DELPHIC 茶馆", kr:"DELPHIC", cat:"咖啡·点心", area:"钟路·北村", members:["崔秀彬", "崔杋圭"], addr:"서울 종로구 계동길 84-3 2층", sub:"SPUR杂志拍摄地;🐰喝的是金盏花牛奶乌龙茶Mili Fili,🐻喝的是橙花柠檬薄荷白茶Katy Did,都是₩9000", src:"官方杂志+粉丝整理", conf:"高", mapq:"계동길 84-3"},
 {id:40, city:"首尔", zh:"NR CERAMICS 陶瓷店", kr:"NR CERAMICS", cat:"购物", area:"钟路·北村", members:["崔秀彬", "崔杋圭"], addr:"서울 종로구 계동길 99 2층", sub:"SPUR杂志拍摄地", src:"官方杂志+粉丝整理", conf:"高", mapq:"계동길 99"},
 {id:41, city:"首尔", zh:"Nostalgia 韩屋", kr:"Nostalgia", cat:"地标", area:"钟路·北村", members:["崔秀彬", "崔杋圭"], addr:"서울 종로구 북촌로11가길 5", sub:"SPUR杂志拍摄地", src:"官方杂志+粉丝整理", conf:"高", mapq:"북촌로11가길 5"},
 {id:42, city:"首尔", zh:"SPACE南山", kr:"SPACE NAMSAN", cat:"地标", area:"中区·南山", members:["崔然竣"], addr:"서울 중구 동호로11길 49", sub:"W Korea(25.09.01)画报拍摄地;1/2/5/6楼", src:"官方杂志+粉丝整理", conf:"高", mapq:"동호로11길 49"},
 {id:43, city:"首尔", zh:"Rubus cafe", kr:"Rubus cafe", cat:"咖啡·点心", area:"汝矣岛", members:["崔然竣"], addr:"서울 영등포구 여의동로 290 이랜드크루즈 제1선착장 1층", sub:"《剧场之我不是独自生活》EP.3同款;在游轮码头里", src:"官方综艺+粉丝整理", conf:"高", mapq:"여의동로 290"},
 {id:44, city:"首尔", zh:"汝矣岛汉江公园鸭子船", kr:"", cat:"玩乐", area:"汝矣岛", members:["崔然竣"], addr:"서울 영등포구 여의동로 252(汝矣岛汉江公园)", sub:"《剧场之我不是独自生活》EP.3同款", src:"官方综艺+粉丝整理", conf:"高", mapq:"여의동로 252"},
 {id:45, city:"首尔", zh:"秘密之林 密室逃脱", kr:"", cat:"玩乐", area:"弘大", members:["崔然竣"], addr:"서울 마포구 잔다리로6길 30 3층", sub:"《剧场之我不是独自生活》EP.3同款", src:"官方综艺+粉丝整理", conf:"高", mapq:"잔다리로6길 30"},
 {id:46, city:"首尔", zh:"Layer Studio 汉南", kr:"Layer Studio", cat:"地标", area:"龙山·汉南", members:["全员"], addr:"서울 용산구 이태원로45길 64", sub:"《Analog》拍摄地;🐻《Panic》Live Clip也在这里拍;摄影棚,需预约才能进", src:"官方内容+粉丝整理", conf:"高", mapq:"이태원로45길 64"},
 {id:47, city:"首尔", zh:"HAUTE-MEAL 燕麦烹饪工作室", kr:"오트밀 쿠킹 스튜디오", cat:"地标", area:"瑞草", members:["全员"], addr:"서울 서초구 언남17길 4 B1-3F", sub:"正规4辑发售派对拍摄地;烹饪工作室,需预约", src:"官方内容+粉丝整理", conf:"高", mapq:"언남17길 4"},
 {id:48, city:"首尔", zh:"首尔公演艺术高中", kr:"서울공연예술고등학교", cat:"地标", area:"九老", members:["全员"], addr:"서울 구로구 오리로22나길 16-26", sub:"《HELLO STRANGERS》拍摄地;学校请在外面拍照", src:"官方内容+粉丝整理", conf:"高", mapq:"서울공연예술고등학교"},
 {id:49, city:"首尔", zh:"世运电子商业街", kr:"세운상가", cat:"地标", area:"钟路", members:["全员"], addr:"서울 종로구 청계천로 159", sub:"《Beautiful Strangers》MV拍摄地", src:"官方MV+粉丝整理", conf:"高", mapq:"청계천로 159"},
 {id:50, city:"首尔", zh:"土巴兔森林(兰芝汉江公园)", kr:"", cat:"地标", area:"麻浦·上岩", members:["全员"], addr:"서울 마포구 상암동 482-224(兰芝汉江公园内)", sub:"TO DO EP.157拍摄地", src:"官方综艺+粉丝整理", conf:"高", mapq:"상암동 482-224"},
 {id:51, city:"首尔", zh:"麻浦渡口(望远汉江公园)", kr:"", cat:"地标", area:"麻浦·望远", members:["全员"], addr:"서울 마포구 마포나루길 442(望远汉江公园内)", sub:"TO DO EP.157拍摄地", src:"官方综艺+粉丝整理", conf:"高", mapq:"마포나루길 442"},
 {id:52, city:"首尔", zh:"TO DO 空隙咖啡厅", kr:"", cat:"咖啡·点心", area:"麻浦·望远", members:["全员"], addr:"서울 마포구 망원로7길 3-6", sub:"TO DO EP.156拍摄地", src:"官方综艺+粉丝整理", conf:"高", mapq:"망원로7길 3-6"},
 {id:53, city:"首尔", zh:"秀KTV", kr:"", cat:"玩乐", area:"弘大", members:["全员"], addr:"서울 마포구 어울마당로 67", sub:"TO DO EP.156拍摄地", src:"官方综艺+粉丝整理", conf:"高", mapq:"어울마당로 67"},
 {id:54, city:"首尔", zh:"我是彬咖啡厅", kr:"", cat:"咖啡·点心", area:"麻浦·阿岘", members:["全员"], addr:"서울 마포구 굴레방로1길 25 상가 111호", sub:"TO DO EP.156拍摄地", src:"官方综艺+粉丝整理", conf:"高", mapq:"굴레방로1길 25"},
 {id:55, city:"首尔", zh:"아마스빈 水色店", kr:"아마스빈 수색점", cat:"咖啡·点心", area:"恩平", members:["全员"], addr:"서울 은평구 수색로 322 아이파크포레 상가 2동 111호", sub:"TO DO EP.156拍摄地;奶茶店", src:"官方综艺+粉丝整理", conf:"高", mapq:"아마스빈 수색점"},
 {id:56, city:"首尔", zh:"植物馆PH", kr:"PH", cat:"咖啡·点心", area:"江南·水西", members:["全员"], addr:"서울 강남구 광평로34길 24", sub:"《Love Language》Performance Video拍摄地;复合文化空间,入场费₩10000;1楼植物间座位就是拍摄地,2楼也有座位", src:"官方内容+粉丝整理", conf:"高", mapq:"광평로34길 24"},
 {id:57, city:"首尔", zh:"华克山庄森林公园", kr:"", cat:"地标", area:"广津", members:["全员"], addr:"서울 광진구 워커힐로 177 워커힐호텔", sub:"《偶像人间剧场》(24.11.09)同款拍摄地", src:"官方综艺+粉丝整理", conf:"高", mapq:"워커힐호텔"},
 {id:58, city:"首尔", zh:"GITTTEUL 烤肉", kr:"깃뜰", cat:"美食", area:"弘大", members:["全员"], addr:"서울 마포구 잔다리로3안길 27 1,2층", sub:"《家大声》同款拍摄地", src:"官方综艺+粉丝整理", conf:"高", mapq:"잔다리로3안길 27"},
 {id:59, city:"首尔", zh:"麻浦新光文化林", kr:"", cat:"地标", area:"麻浦", members:["姜太显"], addr:"서울 마포구 토정로 56", sub:"《To Reach You》拍摄地", src:"官方内容+粉丝整理", conf:"高", mapq:"토정로 56"},
 {id:60, city:"首尔", zh:"Cacti Gacha 扭蛋店 钟阁店", kr:"Cacti Gacha", cat:"玩乐", area:"钟路", members:["崔秀彬"], addr:"서울 종로구 종로12길 9 1~2층", sub:"🐰ins(25.06.05)更新同款", src:"成员ins+粉丝整理", conf:"高", mapq:"종로12길 9"},
 {id:61, city:"首尔", zh:"京义线林间路 舍廊房", kr:"", cat:"地标", area:"龙山", members:["崔秀彬", "崔杋圭"], addr:"서울 용산구 신계동 1-276", sub:"🐰ins(24.01.05)、🐻ins(24.01.03)都更新过同款;蓝色小火车车厢", src:"成员ins+粉丝整理", conf:"高", mapq:"신계동 1-276"},
 {id:62, city:"首尔", zh:"ARCH 首尔 龙山店", kr:"ARCH", cat:"美食", area:"龙山", members:["休宁凯"], addr:"서울 용산구 한강대로52길 25-8 201호,202호", sub:"🐧姐姐ins(25.06.05)更新同款;休宁家族set:纽约客牛排₩69000+酱汁章鱼₩31500+烟熏蒜油虾₩26500+茄汁意面₩25500,总计约806元", src:"家人ins+粉丝整理", conf:"中", mapq:"한강대로52길 25-8"},
 {id:63, city:"日本·东京", zh:"NOA COFFEE", kr:"NOA COFFEE", cat:"咖啡·点心", area:"涩谷·神宫前", members:["崔然竣"], addr:"1 Chome-17-5 Jingumae, Shibuya, Tokyo 150-0001", sub:"🦊IG里的美食;🦊pick:抹茶草莓华夫饼(Matcha Strawberry Waffle)1700日元;不是特别甜的甜品店", src:"成员ins+粉丝整理", conf:"高", mapq:"NOA COFFEE 1-17-5 Jingumae"},
 {id:64, city:"日本·东京", zh:"LUKE'S LOBSTER", kr:"LUKE'S LOBSTER", cat:"美食", area:"连锁店", members:["崔然竣"], addr:"连锁店,东京新宿/表参道都有", sub:"🦊IG里的美食;🦊pick:龙虾卷Lobster Roll Regular 2680日元;龙虾肉多但是冷的,不能接受的宝宝慎重", src:"成员ins+粉丝整理", conf:"高", mapq:"LUKE'S LOBSTER Tokyo"},
 {id:65, city:"日本·东京", zh:"俺流塩拉面", kr:"俺流塩ラーメン", cat:"美食", area:"连锁店", members:["崔然竣"], addr:"连锁店,东京多家", sub:"🦊IG里的美食;🦊pick:柚子盐拉面(ゆず塩)980日元;据说是东京最好吃的拉面之一", src:"成员ins+粉丝整理", conf:"高", mapq:"俺流塩ラーメン"},
 {id:66, city:"首尔", zh:"汝矣岛汉江公园", kr:"여의도한강공원", cat:"地标", area:"汝矣岛", members:["崔然竣"], addr:"서울 영등포구 여의동로 330 여의도한강공원", sub:"《剧场之我不是独自生活》EP.2同款拍摄地", src:"官方综艺+粉丝整理", conf:"高", mapq:"여의동로 330"},
 {id:67, city:"首尔", zh:"金红 中餐厅", kr:"금홍", cat:"美食", area:"江南·论岘", members:["全员"], addr:"서울 강남구 논현로149길 35", sub:"《Our SANCTUARY》同款;根据🐧说的'再往前走一点有一家经常去的中餐厅'推测是这家,请酌情", src:"官方内容+粉丝推测", conf:"低", mapq:"논현로149길 35"}
];
